name: analizer-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: make setup

    - name: Run linter
      run: make lint

    - name: Run Feature tests
      run: make test
